services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '2999:3000'
    environment:
      - NODE_ENV=production
    volumes:
      - /app/node_modules
    command: npm run start

